### PR TITLE
Optimization for `asap-alchemy status -a`

### PR DESCRIPTION
**Pull request by dotsdl**
## Description
Partially addresses #985.

Should speed up the display of statuses for networks with actioned `waiting` or
`running` `Task`s.

## Status
- [x] Ready to go

## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

### CODE REVIEW

**Comment by dotsdl** [comment]
Working on fixing the mocks in the test suite next.

**Comment by hmacdope** [comment]
This worked well for the Falcbot in https://github.com/asapdiscovery/FALCBot/pull/23

**Comment by JenkeScheen** [comment]
@dotsdl what's the status on this PR? Do you need a hand / review?

**Comment by jthorton** [comment]
Updated the tests for these changes and got pre-commit back online hence the large number of changes. I think we can merge this one and tackle the other updates in another PR. cc @JenkeScheen

**Review by JenkeScheen — APPROVED** [review]
LGTM Josh - thanks!

**Pull request merged**
