### PR TITLE
`asap-alchemy prep alchemize`

### PR DESCRIPTION
**Pull request by JenkeScheen**
We want to be able to run alchemy for P3 but it’s HtL so chemistry is much more diverse. We want to be able to find the maximum number of sub-networks we can run from a set like e.g. https://asap.postera.ai/molecule-set/7eaecca8-25b9-4e1e-9a2f-87336fc9d791?viewer=7eaecca8-25b9-4e1e-9a2f-87336fc9d791

and then generate SDF files (for now) for the clusters so that we can feed each of those into `asap-alchemy prep run`.

## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

### CODE REVIEW

**Comment by JenkeScheen** [comment]
this is already quite fast on an M2 macbook pro:
image
and should scale linearly. We'll need to implement multiprocessing if we ever go to sets of thousands.

**Comment by JenkeScheen** [comment]
OK - now with SDF writing enabled:
image

We should discuss how we're going to actually implement this thing, currently it's way too monolithic; a few of the methods should probably be migrated elsewhere. Also still need to write tests.

**Comment by JenkeScheen** [comment]
tested this on a larger set, still runs nicely on only a single processor: 
image

**Comment by JenkeScheen** [comment]
parking for now, will figure out where this should live after my leave.

**Comment by JenkeScheen** [comment]
@hmacdope this is quite complete now - can you have a look through and if you're feeling it perhaps add multiprocessing that works correctly with `tqdm` in `alchemize.rescue_outsiders()`?

**Review by hmacdope — CHANGES_REQUESTED** [review]
Looking great. I just re-jigged the tests a little bit. 

Only question is why is default Mac1 structure changed? 

Re parallelisation, I think lets leave it for now. We can revisit if its a consistent annoyance / blocker.

**Comment by JenkeScheen** [comment]
good catch on mac1! That's definitely not intended.

**Review by hmacdope — APPROVED** [review]

**Pull request merged**
