### PR TITLE
Compatibility testing for openfe and gufe 1.0

### PR DESCRIPTION
**Pull request by dotsdl**
## Description

We wish to execute our CI against `gufe` and `openfe` to check for compatibility issues. This will allow us to fix these issues in anticipation of deployment of these libraries to alchemiscale.org.

## Status
- [ ] Ready to go

## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

### CODE REVIEW

**Comment by dotsdl** [comment]
Looks like `alchemiscale-client` is stopping us here, which is actually by design. We frankly don't want to crank `asap-alchemy` forward to `openfe` and `gufe` 1.0 compatibility until we have this compatibility in `alchemiscale` itself.

Parking this one for now until we clear that, which will come once `openfe` and `gufe` are passed their 1.0 release candidates.

**Comment by dotsdl** [comment]
Will pick this one back up after [alchemiscale 0.5.0](https://github.com/openforcefield/alchemiscale/milestone/12) is released!

**Comment by dotsdl** [comment]
Can now pick this back up! Hitting next!

@hmacdope I think I need to be added as a collaborator or to the org to be able to continue on this one!

**Comment by hmacdope** [comment]
Emergency fix for some of these on #1170, needed for project support. Perhaps best to continue there?

**Comment by dotsdl** [comment]
@hmacdope yes, can do!

**Pull request closed without merging**
