### PR TITLE
[DNM] OpenFE 1.0 + Alchemiscale 0.5 compat

### PR DESCRIPTION
**Pull request by JenkeScheen**
## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

### CODE REVIEW

**Comment by dotsdl** [comment]
@jthorton it looks like we'll have to regenerate the source files for `tyk2_fec_network` and `tyk2_result_network` fixtures, corresponding to `tyk2_small_network.json` and `tyk2_result_network.json`, respectively.

Can you point me to how you generated these files in the first place?

**Comment by dotsdl** [comment]
Awesome, thank you so much @jthorton! If you can commit the scripts and the new schema to this PR, I can take it from there I think!

**Comment by jthorton** [comment]
We have a strange error in the CI from gufe when trying to create an atom mapper class. 
```cls = <class 'openfe.setup.atom_mapping.perses_mapper.PersesAtomMapper'>
args = ()
kwargs = {'allow_ring_breaking': True, 'coordinate_tolerance': 0.15, 'preserve_chirality': True, 'use_positions': True}

    def __call__(cls, *args, **kwargs):
>       instance = super().__call__(*args, **kwargs)
E       TypeError: Can't instantiate abstract class PersesAtomMapper with abstract methods _defaults, _from_dict, _to_dict

../../../micromamba/envs/asapdiscovery/lib/python3.10/site-packages/gufe/tokenization.py:66: TypeError
```
This error does not come up when making a fresh env locally with only openfe and gufe.

**Comment by jthorton** [comment]
The CI error is picking up an issue in openfe see this PR https://github.com/OpenFreeEnergy/openfe/pull/929 for the fix.

**Comment by hmacdope** [comment]
Thanks for investigating this @jthorton! Great detective work. Given this is upstream, lets just XFAIL this on our end until we get a fix.

**Comment by hmacdope** [comment]
#1187 should fix unrelated errors.

**Comment by dotsdl** [comment]
@jthorton I saw you made creating `Task`s a submit parameter in [79ce9a5](https://github.com/asapdiscovery/asapdiscovery/pull/1170/commits/79ce9a5fd1dedbc7ab83e42502c115d807d07762). Thanks for this!

I think it may make sense to go further (in a separate PR) and make setting+actioning `Task`s a separate CLI command. I'll make an issue for this.

**Review by hmacdope — APPROVED** [review]
This looks ready to go!

**Pull request merged**
